// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookmarkController from "./bookmark_controller"
application.register("bookmark", BookmarkController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import ControllerController from "./controller_controller"
application.register("controller", ControllerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import TetrisBackgroundController from "./tetris_background_controller"
application.register("tetris-background", TetrisBackgroundController)
